# -*- coding: utf-8 -*-
"""TextDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imrwnGU9rJ62qbLcEQcVis-V0TPdmMFv
"""

!pip install opencv-python scikit-learn

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils import class_weight

import tensorflow as tf
from tensorflow.keras import layers, models

DATA_PATH = '/content/drive/MyDrive/fabric_project/carpet'

IMG_SIZE = 224

def load_mvtec_data(base_path):
    images = []
    labels = []

    # TRAIN GOOD → label 0
    train_good = os.path.join(base_path, 'train', 'good')

    for file in os.listdir(train_good):
        img = cv2.imread(os.path.join(train_good, file))
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img / 255.0

        images.append(img)
        labels.append(0)

    # TEST (GOOD + DEFECT)
    test_path = os.path.join(base_path, 'test')

    for folder in os.listdir(test_path):
        folder_path = os.path.join(test_path, folder)

        for file in os.listdir(folder_path):
            img = cv2.imread(os.path.join(folder_path, file))
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0

            images.append(img)

            if folder == 'good':
                labels.append(0)
            else:
                labels.append(1)

    return np.array(images), np.array(labels)

X, y = load_mvtec_data(DATA_PATH)

print("Data shape:", X.shape)
print("Labels:", np.unique(y))

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = {0: weights[0], 1: weights[1]}
print(class_weights)

def build_model():
    model = models.Sequential([
        layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(64, (3,3), activation='relu'),
        layers.MaxPooling2D(2,2),

        layers.Conv2D(128, (3,3), activation='relu'),
        layers.MaxPooling2D(2,2),

        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),

        layers.Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

model = build_model()
model.summary()

history = model.fit(
    X_train, y_train,
    epochs=10,
    validation_data=(X_test, y_test),
    batch_size=32,
    class_weight=class_weights
)

plt.plot(history.history['accuracy'], label='train')
plt.plot(history.history['val_accuracy'], label='val')
plt.legend()
plt.title("Accuracy")
plt.show()

y_pred = (model.predict(X_test) > 0.5).astype("int32")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

model.save('/content/drive/MyDrive/fabric_project/fabric_model.h5')

from tensorflow.keras.applications import MobileNetV2

def build_model_2():
    base_model = MobileNetV2(
        weights='imagenet',   # allowed for comparison
        include_top=False,
        input_shape=(224,224,3)
    )

    # Freeze most layers
    for layer in base_model.layers:
        layer.trainable = False

    x = base_model.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    output = layers.Dense(1, activation='sigmoid')(x)

    model = models.Model(inputs=base_model.input, outputs=output)

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

model2 = build_model_2()
model2.summary()

history2 = model2.fit(
    X_train, y_train,
    epochs=10,
    validation_data=(X_test, y_test),
    batch_size=32,
    class_weight=class_weights
)

y_pred2 = (model2.predict(X_test) > 0.5).astype("int32")

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

print("Model 1 Accuracy:", max(history.history['val_accuracy']))
print("Model 2 Accuracy:", max(history2.history['val_accuracy']))

model2.save('/content/drive/MyDrive/fabric_project/fabric_model2.keras')